
server:
    port: 8400
    
# 配置 dev 环境
spring:
    profiles: dev
    application:
        name: abcmsc-provider-depart
    # 配置 spring-data-jpa
    jpa:
        # 指定是否在 Spring 容器启动时创建表，默认为 false
        generate-ddl: true
        # 指定是否在控制台显示 SQL 语句，默认为 false
        show-sql: true
        # 指定应用重启时不重新更新表
        hibernate:
            ddl-auto: none
    # 配置数据源
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql:///test02?useUnicode=true&amp;characterEncoding=UTF-8
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
        
eureka:
    # 指定 eureka 服务中心
    client:
        service-url:
            defaultZone: http://localhost:8000/eureka/
---
# 配置 test 环境
server:
    port: 8500
spring:
    profiles: test
    # 指定当前微服务对外暴露的名称
    application:
        name: abcmsc-provider-depart
    # 配置 spring-data-jpa
    jpa:
        # 指定是否在 Spring 容器启动时创建表，默认为 false
        generate-ddl: true
        # 指定是否在控制台显示 SQL 语句，默认为 false
        show-sql: true
        # 指定应用重启时不重新更新表
        hibernate:
            
    # 配置数据源
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql:///test03?useUnicode=true&amp;characterEncoding=UTF-8
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
eureka:
    # 指定 eureka 服务中心
    client:
        service-url:
            defaultZone: http://localhost:8000/eureka/